-- ============================================================
-- DataDose Pipeline - Snowflake Session Setup
-- ============================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PHARMA_WH;
USE DATABASE PHARMA_ANALYTICS_DB;

-- Quick schema inventory check
SHOW TABLES IN SCHEMA STAGING;
SHOW TABLES IN SCHEMA DIMENSIONS;
SHOW TABLES IN SCHEMA FACTS;
SHOW TABLES IN SCHEMA ANALYTICS;


-- ============================================================
-- TASK 1: Load DIM_DRUG from unprocessed staging rows
-- ============================================================
CREATE OR REPLACE TASK STAGING.TASK_LOAD_DIM_DRUG
  WAREHOUSE = PHARMA_WH
  SCHEDULE = '2 MINUTE'
AS
MERGE INTO DIMENSIONS.DIM_DRUG tgt
USING (
    SELECT DISTINCT
        DRUG AS DRUG_NK,
        DRUG AS TRADE_NAME
    FROM STAGING.STG_TRANSACTION
    WHERE DRUG IS NOT NULL
      AND IS_PROCESSED = FALSE
) src
ON tgt.DRUG_NK = src.DRUG_NK AND tgt.IS_CURRENT = TRUE
WHEN NOT MATCHED THEN
    INSERT (DRUG_NK, TRADE_NAME, SOURCE_SYSTEM)
    VALUES (src.DRUG_NK, src.TRADE_NAME, 'DERIVED_FROM_TRANSACTION');


-- ============================================================
-- TASK 2: Load DIM_PHARMACY from unprocessed staging rows
-- ============================================================
CREATE OR REPLACE TASK STAGING.TASK_LOAD_DIM_PHARMACY
  WAREHOUSE = PHARMA_WH
  SCHEDULE = '2 MINUTE'
AS
MERGE INTO DIMENSIONS.DIM_PHARMACY tgt
USING (
    SELECT DISTINCT
        PHARMACY AS PHARMACY_NK,
        PHARMACY AS PHARMACY_NAME,
        CITY
    FROM STAGING.STG_TRANSACTION
    WHERE IS_PROCESSED = FALSE
      AND PHARMACY IS NOT NULL
) src
ON tgt.PHARMACY_NK = src.PHARMACY_NK
WHEN NOT MATCHED THEN
    INSERT (PHARMACY_NK, PHARMACY_NAME, CITY, COUNTRY)
    VALUES (src.PHARMACY_NK, src.PHARMACY_NAME, src.CITY, 'Egypt');


-- ============================================================
-- TASK 3: Load FACT_PRESCRIPTION_TRANSACTION
-- Runs after DIM_PHARMACY load completes
-- ============================================================
CREATE OR REPLACE TASK STAGING.TASK_LOAD_FACT_PRESCRIPTION
  WAREHOUSE = PHARMA_WH
  AFTER STAGING.TASK_LOAD_DIM_PHARMACY
AS
INSERT INTO FACTS.FACT_PRESCRIPTION_TRANSACTION (
    TX_ID, DRUG_SK, PHARMACY_SK, TX_DATE_SK, LOAD_DATE_SK,
    IS_NEW_PRESCRIPTION, DRUG_NAME_AS_DISPENSED,
    CURRENT_MEDS, CURRENT_MEDS_COUNT, POLYPHARMACY_FLAG,
    INTERACTION_FOUND, INTERACTION_COUNT, INTERACTING_DRUGS,
    INTERACTION_SEVERITY, INTERACTION_TYPE,
    ACTIVE_INGREDIENT_MATCH, SHARED_INGREDIENT, INGREDIENT_OVERLAP_COUNT,
    HIGH_RISK_PATIENT, DRUG_RISK_SCORE, PATIENT_RISK_SCORE, INTERACTION_RATE,
    STG_BATCH_ID, SOURCE_SYSTEM
)
SELECT
    s.TX_ID,
    COALESCE(d.DRUG_SK, -1)                                          AS DRUG_SK,
    p.PHARMACY_SK,
    TO_NUMBER(TO_CHAR(s.LOAD_TIMESTAMP::DATE, 'YYYYMMDD'))           AS TX_DATE_SK,
    TO_NUMBER(TO_CHAR(CURRENT_DATE(), 'YYYYMMDD'))                   AS LOAD_DATE_SK,
    (s.IS_NEW_PRESCRIPTION = 'New')                                  AS IS_NEW_PRESCRIPTION,
    s.DRUG,
    s.CURRENT_MEDS,
    TRY_CAST(s.CURRENT_MEDS_COUNT AS NUMBER),
    (s.POLYPHARMACY_FLAG = 'TRUE'),
    (s.INTERACTION_FOUND = 'TRUE'),
    TRY_CAST(s.INTERACTION_COUNT AS NUMBER),
    s.INTERACTING_DRUGS,
    NULLIF(s.INTERACTION_SEVERITY, ''),
    NULLIF(s.INTERACTION_TYPE, ''),
    (s.ACTIVE_INGREDIENT_MATCH = 'TRUE'),
    s.SHARED_INGREDIENT,
    TRY_CAST(s.INGREDIENT_OVERLAP_COUNT AS NUMBER),
    (s.HIGH_RISK_PATIENT = 'TRUE'),
    TRY_CAST(s.DRUG_RISK_SCORE AS NUMBER),
    TRY_CAST(s.PATIENT_RISK_SCORE AS NUMBER),
    TRY_CAST(s.INTERACTION_RATE AS NUMBER),
    s.BATCH_ID,
    s.SOURCE_SYSTEM
FROM STAGING.STG_TRANSACTION s
LEFT JOIN DIMENSIONS.DIM_PHARMACY p ON p.PHARMACY_NK = s.PHARMACY
LEFT JOIN DIMENSIONS.DIM_DRUG     d ON d.TRADE_NAME  = s.DRUG AND d.IS_CURRENT = TRUE
WHERE s.IS_PROCESSED = FALSE
  AND p.PHARMACY_SK IS NOT NULL;


-- ============================================================
-- TASK 4: Mark staging rows as processed
-- Runs after FACT load completes
-- ============================================================
CREATE OR REPLACE TASK STAGING.TASK_MARK_PROCESSED
  WAREHOUSE = PHARMA_WH
  AFTER STAGING.TASK_LOAD_FACT_PRESCRIPTION
AS
UPDATE STAGING.STG_TRANSACTION s
SET IS_PROCESSED = TRUE
WHERE IS_PROCESSED = FALSE
  AND EXISTS (
      SELECT 1 FROM FACTS.FACT_PRESCRIPTION_TRANSACTION f
      WHERE f.TX_ID = s.TX_ID
  );


-- ============================================================
-- TASK 5: Refresh PHARMACY_RISK_SUMMARY analytics table
-- Runs after staging rows are marked processed
-- ============================================================
CREATE OR REPLACE TASK STAGING.TASK_REFRESH_PHARMACY_RISK_SUMMARY
  WAREHOUSE = PHARMA_WH
  AFTER STAGING.TASK_MARK_PROCESSED
AS
MERGE INTO ANALYTICS.PHARMACY_RISK_SUMMARY tgt
USING (
    SELECT
        f.PHARMACY_SK,
        f.TX_DATE_SK                                         AS SUMMARY_DATE_SK,
        p.PHARMACY_NAME,
        p.CITY,
        COUNT(*)                                              AS TOTAL_PRESCRIPTIONS,
        SUM(IFF(f.INTERACTION_FOUND, 1, 0))                   AS TOTAL_INTERACTIONS_DETECTED,
        COUNT(DISTINCT IFF(f.HIGH_RISK_PATIENT, f.TX_SK, NULL)) AS HIGH_RISK_PATIENT_COUNT,
        COUNT(DISTINCT IFF(f.POLYPHARMACY_FLAG, f.TX_SK, NULL)) AS POLYPHARMACY_PATIENT_COUNT,
        AVG(f.PATIENT_RISK_SCORE)                             AS AVG_PATIENT_RISK_SCORE,
        AVG(f.DRUG_RISK_SCORE)                                AS AVG_DRUG_RISK_SCORE,
        SUM(IFF(f.INTERACTION_FOUND,1,0)) / NULLIF(COUNT(*),0) AS INTERACTION_RATE,
        SUM(IFF(f.INTERACTION_SEVERITY = 'Major',1,0))        AS MAJOR_INTERACTION_COUNT,
        SUM(IFF(f.INTERACTION_SEVERITY = 'Moderate',1,0))     AS MODERATE_INTERACTION_COUNT,
        SUM(IFF(f.INTERACTION_SEVERITY = 'Minor',1,0))        AS MINOR_INTERACTION_COUNT
    FROM FACTS.FACT_PRESCRIPTION_TRANSACTION f
    JOIN DIMENSIONS.DIM_PHARMACY p ON f.PHARMACY_SK = p.PHARMACY_SK
    GROUP BY f.PHARMACY_SK, f.TX_DATE_SK, p.PHARMACY_NAME, p.CITY
) src
ON tgt.PHARMACY_SK = src.PHARMACY_SK AND tgt.SUMMARY_DATE_SK = src.SUMMARY_DATE_SK
WHEN MATCHED THEN UPDATE SET
    tgt.TOTAL_PRESCRIPTIONS = src.TOTAL_PRESCRIPTIONS,
    tgt.TOTAL_INTERACTIONS_DETECTED = src.TOTAL_INTERACTIONS_DETECTED,
    tgt.HIGH_RISK_PATIENT_COUNT = src.HIGH_RISK_PATIENT_COUNT,
    tgt.POLYPHARMACY_PATIENT_COUNT = src.POLYPHARMACY_PATIENT_COUNT,
    tgt.AVG_PATIENT_RISK_SCORE = src.AVG_PATIENT_RISK_SCORE,
    tgt.AVG_DRUG_RISK_SCORE = src.AVG_DRUG_RISK_SCORE,
    tgt.INTERACTION_RATE = src.INTERACTION_RATE,
    tgt.MAJOR_INTERACTION_COUNT = src.MAJOR_INTERACTION_COUNT,
    tgt.MODERATE_INTERACTION_COUNT = src.MODERATE_INTERACTION_COUNT,
    tgt.MINOR_INTERACTION_COUNT = src.MINOR_INTERACTION_COUNT,
    tgt.COMPUTED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    PHARMACY_SK, SUMMARY_DATE_SK, PHARMACY_NAME, CITY,
    TOTAL_PRESCRIPTIONS, TOTAL_INTERACTIONS_DETECTED,
    HIGH_RISK_PATIENT_COUNT, POLYPHARMACY_PATIENT_COUNT,
    AVG_PATIENT_RISK_SCORE, AVG_DRUG_RISK_SCORE, INTERACTION_RATE,
    MAJOR_INTERACTION_COUNT, MODERATE_INTERACTION_COUNT, MINOR_INTERACTION_COUNT
)
VALUES (
    src.PHARMACY_SK, src.SUMMARY_DATE_SK, src.PHARMACY_NAME, src.CITY,
    src.TOTAL_PRESCRIPTIONS, src.TOTAL_INTERACTIONS_DETECTED,
    src.HIGH_RISK_PATIENT_COUNT, src.POLYPHARMACY_PATIENT_COUNT,
    src.AVG_PATIENT_RISK_SCORE, src.AVG_DRUG_RISK_SCORE, src.INTERACTION_RATE,
    src.MAJOR_INTERACTION_COUNT, src.MODERATE_INTERACTION_COUNT, src.MINOR_INTERACTION_COUNT
);


-- ============================================================
-- Resume tasks in reverse dependency order (children first, roots last)
-- ============================================================
ALTER TASK STAGING.TASK_REFRESH_PHARMACY_RISK_SUMMARY RESUME;
ALTER TASK STAGING.TASK_MARK_PROCESSED RESUME;
ALTER TASK STAGING.TASK_LOAD_FACT_PRESCRIPTION RESUME;
ALTER TASK STAGING.TASK_LOAD_DIM_PHARMACY RESUME;
ALTER TASK STAGING.TASK_LOAD_DIM_DRUG RESUME;

-- Confirm all tasks exist and their current state
SHOW TASKS IN DATABASE PHARMA_ANALYTICS_DB;


-- ============================================================
-- Validation checks (row counts across the pipeline)
-- ============================================================

-- DIM_DRUG populated?
SELECT COUNT(*) FROM DIMENSIONS.DIM_DRUG;

-- DIM_PHARMACY populated?
SELECT COUNT(*) FROM DIMENSIONS.DIM_PHARMACY;

-- FACT table populated?
SELECT COUNT(*) FROM FACTS.FACT_PRESCRIPTION_TRANSACTION;

-- ANALYTICS table populated?
SELECT COUNT(*) FROM ANALYTICS.PHARMACY_RISK_SUMMARY;

-- Staging rows marked as processed?
SELECT COUNT(*) FROM STAGING.STG_TRANSACTION WHERE IS_PROCESSED = TRUE;

-- Recent task run history
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC
LIMIT 30;


-- ============================================================
-- Emergency suspend (uncomment if needed)
-- ============================================================
-- ALTER TASK STAGING.TASK_LOAD_DIM_PHARMACY SUSPEND;
-- ALTER TASK STAGING.TASK_LOAD_DIM_DRUG SUSPEND;
-- ALTER TASK STAGING.TASK_LOAD_FACT_PRESCRIPTION SUSPEND;
-- ALTER TASK STAGING.TASK_MARK_PROCESSED SUSPEND;
-- ALTER TASK STAGING.TASK_REFRESH_PHARMACY_RISK_SUMMARY SUSPEND;
