USE ROLE ACCOUNTADMIN;

-- Create dedicated PySpark role
CREATE ROLE IF NOT EXISTS PYSPARK_ROLE;

-- Grant database + schema access
GRANT USAGE ON DATABASE PHARMA_ANALYTICS_DB TO ROLE PYSPARK_ROLE;
GRANT USAGE ON ALL    SCHEMAS IN DATABASE PHARMA_ANALYTICS_DB TO ROLE PYSPARK_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PHARMA_ANALYTICS_DB TO ROLE PYSPARK_ROLE;
-- Grant table access (current + future)
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL    TABLES IN DATABASE PHARMA_ANALYTICS_DB TO ROLE PYSPARK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON FUTURE TABLES IN DATABASE PHARMA_ANALYTICS_DB TO ROLE PYSPARK_ROLE;

-- Per-schema grants (belt-and-suspenders approach)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL    TABLES IN SCHEMA PHARMA_ANALYTICS_DB.STAGING    TO ROLE PYSPARK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PHARMA_ANALYTICS_DB.STAGING    TO ROLE PYSPARK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL    TABLES IN SCHEMA PHARMA_ANALYTICS_DB.DIMENSIONS TO ROLE PYSPARK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PHARMA_ANALYTICS_DB.DIMENSIONS TO ROLE PYSPARK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL    TABLES IN SCHEMA PHARMA_ANALYTICS_DB.FACTS      TO ROLE PYSPARK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PHARMA_ANALYTICS_DB.FACTS      TO ROLE PYSPARK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL    TABLES IN SCHEMA PHARMA_ANALYTICS_DB.ANALYTICS  TO ROLE PYSPARK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PHARMA_ANALYTICS_DB.ANALYTICS  TO ROLE PYSPARK_ROLE;

-- Grant view access
GRANT SELECT ON ALL    VIEWS IN SCHEMA PHARMA_ANALYTICS_DB.ANALYTICS TO ROLE PYSPARK_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMA_ANALYTICS_DB.ANALYTICS TO ROLE PYSPARK_ROLE;

-- Grant warehouse compute
GRANT USAGE ON WAREHOUSE PHARMA_WH TO ROLE PYSPARK_ROLE;

-- Create service user (CHANGE PASSWORD BEFORE RUNNING)
CREATE USER IF NOT EXISTS PYSPARK_SVC
    PASSWORD             = 'DataDoseAzure2025!'
    DEFAULT_ROLE         = PYSPARK_ROLE
    DEFAULT_WAREHOUSE    = PHARMA_WH
    DEFAULT_NAMESPACE    = PHARMA_ANALYTICS_DB.STAGING
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE PYSPARK_ROLE TO USER PYSPARK_SVC;
GRANT ROLE PYSPARK_ROLE TO USER DataDose;

-- Verify
SHOW GRANTS TO USER PYSPARK_SVC;
SHOW GRANTS TO USER DataDose;
USE ROLE ACCOUNTADMIN;
