
-- BLOCK 0: WAREHOUSE (run first)
CREATE WAREHOUSE IF NOT EXISTS PHARMA_WH
    WAREHOUSE_SIZE      = 'X-SMALL'
    AUTO_SUSPEND        = 60
    AUTO_RESUME         = TRUE
    INITIALLY_SUSPENDED = FALSE;

USE WAREHOUSE PHARMA_WH;

-- BLOCK 1: DATABASE + SCHEMAS
CREATE DATABASE IF NOT EXISTS PHARMA_ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS PHARMA_ANALYTICS_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS PHARMA_ANALYTICS_DB.DIMENSIONS;
CREATE SCHEMA IF NOT EXISTS PHARMA_ANALYTICS_DB.FACTS;
CREATE SCHEMA IF NOT EXISTS PHARMA_ANALYTICS_DB.ANALYTICS;
USE DATABASE PHARMA_ANALYTICS_DB;
