-- ============================================================
-- DataDose: RBAC Approval Workflow Migration
-- Run this in: Supabase Dashboard → SQL Editor
-- Purpose: Add SUPER_ADMIN role, ApprovalStatus enum, and
--          new status + verificationDocument fields to User.
-- ============================================================

-- 1. Add SUPER_ADMIN to the Role enum
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';

-- 2. Create the ApprovalStatus enum
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ApprovalStatus') THEN
        CREATE TYPE "ApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
    END IF;
END$$;

-- 3. Add "status" column with default PENDING (new users are always pending)
ALTER TABLE "User"
    ADD COLUMN IF NOT EXISTS "status" "ApprovalStatus" NOT NULL DEFAULT 'PENDING';

-- 4. Add optional verificationDocument column
ALTER TABLE "User"
    ADD COLUMN IF NOT EXISTS "verificationDocument" TEXT;

-- 5. Approve all EXISTING users (they were registered before the
--    approval workflow existed, so they should not be locked out).
UPDATE "User" SET "status" = 'APPROVED' WHERE "status" = 'PENDING';

-- 6. Seed the Super Admin account (upsert pattern)
-- IMPORTANT: Replace the password hash below with a bcrypt hash of your actual password.
-- The hash below is bcrypt('password123', 10) — generated by the seed script.
INSERT INTO "User" (id, email, name, password, role, status, "createdAt")
VALUES (
    gen_random_uuid()::text,
    'youssef@datadose.ai',
    'Youssef Super Admin',
    '$2b$10$1rKQFo2EjQS.LLE842Z4fuQ860kgzCmJ6XKwaXPtkiw.wpFCiOuVQOC',
    'SUPER_ADMIN',
    'APPROVED',
    NOW()
)
ON CONFLICT (email) DO UPDATE
    SET role = 'SUPER_ADMIN', status = 'APPROVED';

-- Done!
SELECT 'Migration complete. SUPER_ADMIN and ApprovalStatus workflow applied.' AS result;
